In [8]:
import pandas as pd
import re
import os

In [27]:
import pandas as pd
import os

df_list = []
error_files = []

for filename in os.listdir("archive"):
    if filename.endswith(".csv"):
        file_path = os.path.join("archive", filename)
        try:
            # Try reading with utf-8 encoding
            df = pd.read_csv(file_path, encoding='utf-8')
        except UnicodeDecodeError:
            # Try ISO encoding if utf-8 fails
            try:
                df = pd.read_csv(file_path, encoding='ISO-8859-1')
            except Exception as e:
                print(f" Could not read {filename}: {e}")
                error_files.append(filename)
                continue
        except Exception as e:
            print(f" Could not read {filename}: {e}")
            error_files.append(filename)
            continue

        # Only keep "Text" column if it exists
        if "Text" in df.columns:
            df_list.append(df[["Text"]])
        else:
            print(f"⚠️ 'Text' column not found in {filename}")
            error_files.append(filename)

# combines all valid DataFrames
combined_df = pd.concat(df_list, ignore_index=True)

# drops NaNs and empty strings
combined_df.dropna(subset=["Text"], inplace=True)
combined_df = combined_df[combined_df["Text"].str.strip() != ""]

# save to new CSV
combined_df.to_csv("tweets0.csv", index=False)

if error_files:
    print("\n skipped files ")
    for ef in error_files:
        print(f" - {ef}")

 Could not read backhand_index_pointing_right.csv: Error tokenizing data. C error: Buffer overflow caught - possible malformed input file.

 Could not read red_heart.csv: Error tokenizing data. C error: Buffer overflow caught - possible malformed input file.


 Combined 41 files. Total rows: 820002

 skipped files
 - backhand_index_pointing_right.csv
 - red_heart.csv

In [20]:
df = pd.read_csv("archive/red_heart.csv", engine='python', on_bad_lines='skip')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20001 entries, 0 to 20000
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Text    20001 non-null  object
dtypes: object(1)
memory usage: 156.4+ KB

In [22]:
df

                                                    Text
0      @chojiVAL true, some human interaction will tr...
1                    Liverpool 2-2 A.Ramsdale 🔥\n#LIVARS
2      I just won R1000 because Arsenal avoided defea...
3              Tap with a  ,❤️, let’s follow you fast ❤️
4      What Ramsdale did for us today will never be f...
...                                                  ...
19996  @DanaTerrace Thank you so much for everything,...
19997                  @kaysportal As you should queen❤️
19998  THEY TOLD ME HE'S THE BEST IN THE BUSINESS😭😭😭😭...
19999  How marvelous😌, how wonderful is our Saviour's...
20000                  We are the gunners ❤️❤️❤️ #LIVARS

[20001 rows x 1 columns]

In [23]:
df2 = pd.read_csv("archive/backhand_index_pointing_right.csv", engine='python', on_bad_lines='skip')

In [26]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20025 entries, 0 to 20024
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Text    20025 non-null  object
dtypes: object(1)
memory usage: 156.6+ KB

In [24]:
df2

                                                    Text
0      🧡@KeplerHomes AirdropBox event for #Arbitrum e...
1      Remember, success in online business is a mara...
2      @occupied_9 @Rhiannon_clare_ @FightHaven Thank...
3      Hungry for active mutuals👬👭? Follow fastest Re...
4      📢 It's confirmed. Whitelist for Shardeum Airdr...
...                                                  ...
20020  @ViolentCrafted Wait I- we have the same hc 😭\...
20021  💜💜💜💜\nWe are 836 on tiktok. I would really lov...
20022  @roodootoo Sorry to hear you're having some is...
20023  @bunniezuku WAAAAHHH THANK YOU 💕💕 i hope you'r...
20024  🚨 Did your Canada student visa application get...

[20025 rows x 1 columns]

In [28]:
combined_df = pd.concat([df, df2], ignore_index=True)

In [29]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40025 entries, 0 to 40024
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Text    40025 non-null  object
dtypes: object(1)
memory usage: 312.8+ KB

In [30]:
combined_df

                                                    Text
0      Didn't that #CovidUK killer🤡 #Johnson do enoug...
1                  He is right.. there was/is no chaos 🤡
2      @TheBlueDodger Dumb and dumber. Taking 40 year...
3      @PureBloodNPC123 @QuadJacksXRP @JoelKatz Yeah,...
4      @AOC I see a bunch of white college communists...
...                                                  ...
40020  @ViolentCrafted Wait I- we have the same hc 😭\...
40021  💜💜💜💜\nWe are 836 on tiktok. I would really lov...
40022  @roodootoo Sorry to hear you're having some is...
40023  @bunniezuku WAAAAHHH THANK YOU 💕💕 i hope you'r...
40024  🚨 Did your Canada student visa application get...

[40025 rows x 1 columns]

In [38]:
df3 = pd.read_csv("tweets0.csv")

In [40]:
full_df = pd.concat([combined_df, df3], ignore_index=True)

In [41]:
full_df

                                                     Text
0       Didn't that #CovidUK killer🤡 #Johnson do enoug...
1                   He is right.. there was/is no chaos 🤡
2       @TheBlueDodger Dumb and dumber. Taking 40 year...
3       @PureBloodNPC123 @QuadJacksXRP @JoelKatz Yeah,...
4       @AOC I see a bunch of white college communists...
...                                                   ...
860022  @chrissennello @CodifyBaseball There’s not a s...
860023  Okay I can spoil how my friend felt about seei...
860024  @Hazel29630360 @FBM_Warrior @JoDivaRunner 🤡 yo...
860025  @KrumelsBunker @EmeraldRobinson @GeorgeMcfly17...
860026  @catturd2 Yes, good morning brainwashed😵‍💫 rig...

[860027 rows x 1 columns]

In [46]:
full_df = full_df.drop_duplicates(subset='Text', keep='first')

In [47]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 811886 entries, 0 to 840026
Data columns (total 1 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Text    811886 non-null  object
dtypes: object(1)
memory usage: 12.4+ MB

In [48]:
full_df = full_df.dropna(subset=['Text'])

In [51]:
# true if tweet consists only of special characters or whitespace
def is_special_chars_only(tweet):
    # Return True if tweet consists only of special characters or whitespace
    return not bool(re.search(r'[a-zA-Z0-9]', tweet))

full_df = full_df[~full_df['Text'].apply(is_special_chars_only)]

In [53]:
# checks if tweet contains only URLs or mentions
def is_url_or_mention(tweet):
    return re.match(r"(http\S+|@\w+)+", tweet) is not None

full_df = full_df[~full_df['Text'].apply(is_url_or_mention)]

In [56]:
# true if tweet consists only of special characters or whitespace
def is_special_chars_only(tweet):
    return not bool(re.search(r'[a-zA-Z0-9]', tweet))

full_df = full_df[~full_df['Text'].apply(is_special_chars_only)]

In [60]:
max_length = 150  # max length of tweet
full_df = full_df[full_df['Text'].apply(lambda x: len(x) <= max_length)]

In [63]:
full_df = full_df[~full_df["Text"].str.contains(r"\n|\t")]

In [66]:
full_df = full_df[~full_df["Text"].str.contains("http", case=False, na=False)]

In [68]:
def has_text_chars(tweet):
    return bool(re.search(r'[a-zA-Z0-9]', tweet))

full_df = full_df[full_df["Text"].apply(has_text_chars)]

In [71]:
def extract_emojis(text):
    return [char for char in str(text) if emoji.is_emoji(char)]

all_emojis = full_df['Text'].dropna().apply(extract_emojis)

flat_emojis = set([emoji for sublist in all_emojis for emoji in sublist])

print(f"Number of unique emojis: {len(flat_emojis)}")
print(flat_emojis)

Number of unique emojis: 1196
{'⛸', '🥜', '🎡', '🏽', '🚁', '♀', '🔰', '🛋', '🦔', '🍾', '🧼', '😁', '😛', '🎇', '🧛', '👒', '🖇', '💾', '🕦', '🌥', '🧰', '🎪', '💭', '🐦', '🫚', '🚀', '⚖', '⁉', '🙎', 'Ⓜ', '🥭', '⛺', '🍎', '🥡', '🌭', '🥟', '🎁', '🖍', '🚪', '🛁', '🗃', '😣', '☮', '💃', '💑', '🉐', '🆗', '🎲', '🗯', '📄', '🥺', '🚠', '🛌', '🐊', '㊗', '🐳', '🫱', '📣', '🎉', '💠', '🍉', '🧔', '📝', '🔄', '🔢', '🦝', '🧆', '🛞', '👾', '✡', '🛠', '🔛', '🥌', '🈴', '🫑', '🍆', '🐏', '🗾', '🌎', '🥽', '🕌', '🍨', '🕶', '🏠', '🪠', '✅', '🎖', '👘', '🐎', '🐤', '〽', '💝', 'ℹ', '🥪', '🌼', '❎', '🏂', '🚓', '🍠', '💶', '👢', '🫰', '🧖', '💽', '🧪', '😐', '🫧', '🫴', '📠', '🤲', '😖', '🏥', '🫸', '🍳', '🎼', '🍧', '👭', '🚕', '🥂', '🪲', '🥳', '🎮', '😻', '⚫', '🆑', '🎱', '✋', '⤵', '👔', '🥩', '🍓', '🧞', '🏩', '⛔', '👫', '🚹', '🎷', '⚰', '🤫', '🫣', '🍭', '🦋', '🚌', '📑', '💐', '🎈', '🎄', '🎑', '🦮', '◾', '⛹', '🦖', '🧲', '🏰', '🍣', '💄', '🪅', '🕚', '⚧', '🙉', '🧳', '🆒', '🦽', '🫀', '🛬', '🔆', '🥹', '💧', '🆙', '🎃', '🦧', '🩵', '🏋', '🚬', '⚾', '🛣', '🛺', '🏨', '⚠', '👖', '✨', '💘', '🎢', '⏱', '🎹', '🎾', '🤧', '🫘', '😊', '🚩', '👮', '🍷', '😔', '🧟', '🔌', '🐶', '🤚', '🎂', '🐆', '🦦', '🔅', '⛓', '👇', '🌱', '🏢', '🟣', '🧦', '🦒', '🦯', '🥷', '⚒', '🚛', '🐙', '🏜', '🧝', '🚘', '☃', '🔗', '🚒', '🎭', '♿', '🚻', '⬆', '☎', '🦩', '🦂', '🐌', '🚜', '🥫', '😅', '🌰', '⏹', '👉', '🤺', '🎛', '🕙', '🐚', '🗝', '🍯', '🍁', '🚥', '😤', '↔', '🌆', '😝', '📡', '💀', '🤤', '🌨', '🟡', '💪', '🎨', '🌧', '🐘', '🍺', '➰', '🫎', '🎸', '💒', '🚚', '🕣', '😌', '⛷', '♑', '🎫', '⚪', '🏎', '🥱', '😵', '💎', '🛂', '🎬', '🤡', '💬', '🍼', '🛡', '🤟', '👎', '🤠', '🤰', '📿', '📳', '⛰', '👱', '🦊', '🍿', '😬', '🔞', '⏪', '🛒', '🥎', '🖊', '🍋', '🤴', '🐪', '🩰', '🎺', '🪒', '🦟', '🗣', '🐣', '🅿', '✂', '🎗', '🌯', '🔂', '⚔', '🗞', '🧁', '🍡', '🔜', '🎧', '📨', '🪐', '🦉', '🛏', '🧱', '🏈', '⚱', '🐺', '♨', '🔎', '♥', '🏦', '🐛', '💇', '🪖', '🤷', '🥶', '🍫', '📐', '🚫', '🤢', '⛪', '♒', '🧈', '☂', '🐽', '🩻', '🚑', '🧉', '🐧', '👟', '🧩', '🧺', '👺', '🌇', '🈵', '🕎', '🐇', '🤣', '🏼', '🐂', '🏔', '🔝', '🖤', '🐋', '🫠', '🥐', '🏄', '🌞', '😮', '😓', '🤐', '🤱', '🗨', '💸', '🤸', '🧾', '🩴', '👆', '📘', '📉', '🕷', '🏯', '🥦', '🍌', '🔐', '☪', '🏊', '🧹', '🐥', '🕯', '🦭', '🔴', '🦇', '🤪', '🙍', '🌙', '👁', '🈶', '🏒', '🤥', '🔹', '🌁', '😀', '🫢', '🧑', '🥢', '🫁', '💯', '🪻', '🧄', '🐟', '😭', '⛅', '🍙', '🔒', '🧓', '📥', '🧬', '🛫', '♉', '🙃', '☀', '🎣', '🤳', '🌟', '🏪', '💢', '📞', '🏹', '😍', '🔱', '🍚', '🍬', '👞', '📛', '▫', '🦴', '🪬', '🚮', '🏭', '⛄', '🐃', '💔', '🥁', '◽', '🤭', '💤', '🕊', '➡', '👕', '🕉', '🍲', '✝', '☠', '💼', '🔔', '😗', '🍖', '🌠', '🏳', '🖌', '🦳', '🏀', '😫', '🔥', '🦺', '🌶', '📍', '♣', '🌩', '♌', '🐅', '🐯', '💣', '🙏', '🥙', '❕', '🧫', '🟠', '👗', '🚲', '✖', '🏣', '♋', '😡', '✒', '🖖', '🗒', '⌨', '♊', '🐖', '💮', '🌐', '🦲', '😦', '🔬', '💍', '🐁', '🪀', '🪶', '☝', '🐹', '🙋', '🫕', '🪞', '🌾', '🕸', '🪩', '👙', '⏰', '😎', '🫖', '🪂', '🔊', '🤏', '🟨', '💡', '💩', '🌚', '🛸', '🤝', '🤖', '📦', '♈', '🍮', '🏍', '🚽', '🤦', '🔭', '🍘', '🦾', '👣', '🧙', '🔘', '🍥', '👰', '🪴', '😨', '🐬', '🚖', '🪟', '🕹', '🌡', '🦍', '☔', '🍍', '🧍', '🦼', '🌸', '🦞', '✉', '😢', '😙', '🤾', '🤎', '💻', '🌉', '🚰', '🪦', '🌈', '🎋', '💉', '🫥', '🌷', '🗳', '🦈', '🐭', '🔪', '🦀', '🐾', '🥝', '📽', '🧴', '🫐', '🦁', '👓', '🦜', '🥮', '🌅', '🗑', '🥗', '😪', '🪿', '🍈', '📹', '🙂', '💋', '🦗', '🎵', '🎀', '🦷', '🫳', '🚤', '⛈', '🏫', '☁', '🐴', '🥵', '😰', '⏳', '🥀', '🕝', '🌖', '👨', '🪑', '🍴', '🔁', '🎥', '🦶', '🅰', '🥲', '⛵', '🫔', '🧿', '♟', '👥', '🌺', '💵', '🪽', '🪄', '🗺', '♏', '🦥', '🌴', '😱', '👈', '📩', '❗', '🍐', '🍂', '🐉', '👸', '🩱', '🍇', '😿', '🦨', '⛏', '✴', '🛎', '🌌', '🏴', '🔑', '👃', '💴', '🧣', '⏩', '🥸', '🔈', '🛍', '🧯', '😆', '🐝', '⚽', '🏕', '🤑', '🐱', '⬛', '🧀', '🏞', '🪰', '🍛', '💨', '🕜', '🎶', '💺', '🤹', '🤛', '⛴', '⛽', '🔫', '☦', '😳', '🚭', '🦎', '💲', '🌵', '👜', '🆘', '🥤', '☺', '🌝', '🌀', '🐞', '😥', '🫨', '⏲', '🧇', '🤘', '📲', '💆', '🦹', '🙈', '🪕', '😞', '🔖', '😜', '🫒', '🏿', '🐑', '👳', '🗽', '💊', '🛶', '☢', '🌽', '🤒', '🏛', '🚙', '🎆', '🐨', '🐲', '🧷', '🫷', '🏅', '🙆', '🦅', '👼', '👯', '😼', '🍊', '🪢', '👴', '💰', '❤', '📟', '🍵', '😟', '☯', '🏏', '🦄', '🐡', '💚', '🚔', '🍏', '⭕', '🌿', '🧅', '⤴', '🫡', '🅾', '🦘', '🏷', '🩷', '🧨', '🫓', '📌', '🪈', '♂', '🍪', '🌍', '®', '🤶', '™', '🤙', '🏝', '😩', '🧽', '🪪', '🐈', '🥈', '🧜', '🔟', '🎰', '🤔', '📷', '⛱', '⛲', '🧭', '🔚', '👩', '🤜', '🥯', '🙁', '◼', '🧋', '👽', '🎟', '🦸', '🤬', '👠', '🫂', '🦠', '🎤', '💗', '🛢', '🔺', '🕺', '🥧', '🩼', '👊', '😕', '💜', '📈', '🪸', '🦻', '🎙', '🥉', '📺', '🤨', '☘', '🪓', '🪇', '🦤', '🐍', '🎐', '🔙', '🥻', '❄', '🗓', '🍢', '🥬', '🌤', '🏃', '➗', '👪', '🥔', '📗', '🎚', '🆎', '🦿', '🧡', '👋', '🏻', '😺', '🌋', '⛳', '🚾', '🐰', '👌', '🥓', '🏤', '⌚', '📼', '🌃', '🌜', '🎞', '🩳', '🛐', '🩶', '🎅', '🩸', '👲', '🪼', '😧', '🆔', '🚴', '🧒', '🔏', '🥊', '😹', '☄', '💟', '🍞', '😸', '🏆', '🍦', '❌', '🍤', '🦵', '🩺', '🗡', '🌄', '▪', '🕵', '🅱', '🪥', '🎒', '😄', '🏓', '📰', '🪣', '🔩', '🔶', '📖', '🍒', '🎍', '🔻', '🦕', '🏌', '📀', '🥴', '🍕', '👛', '🚗', '🌊', '♓', '💛', '😚', '🖲', '♦', '🏘', '🟢', '🧐', '🛟', '🕒', '🥄', '🫦', '🍀', '☕', '🐼', '🥇', '😾', '🔦', '🎩', '🧗', '🍸', '💁', '♐', '🧊', '📜', '🤼', '🍃', '🙅', '🏬', '⏯', '🫲', '😲', '🗿', '🐕', '🟥', '🪱', '📱', '🥚', '⚓', '🏉', '©', '🛅', '🏾', '🤯', '🎳', '💌', '💙', '🩲', '😴', '👬', '👐', '🥖', '🐩', '👑', '🛕', '🍩', '🖼', '😠', '🟩', '📊', '🦚', '🌗', '🥰', '💫', '✊', '😏', '🔮', '🌬', '🔃', '💂', '🌮', '🤍', '🧤', '🙄', '🍅', '🧠', '🪙', '🌔', '😈', '👏', '🦢', '🌦', '⌛', '🧶', '🦏', '🛹', '🐀', '👦', '⬇', '⚡', '🚶', '💅', '🍜', '🍔', '🌏', '🌪', '➕', '🐓', '🥥', '👅', '😑', '🚿', '😒', '🛳', '♻', '🧵', '🦃', '⭐', '🕠', '💕', '👍', '☑', '😃', '♾', '💓', '🔕', '〰', '🪷', '🔓', '😘', '🪺', '💳', '🪳', '🤞', '🔋', '🥾', '👚', '🛩', '🛰', '🦌', '❇', '🐸', '🦬', '🧃', '🕴', '🔨', '🕛', '🌕', '🃏', '🔵', '💱', '📢', '🦪', '🪫', '🛑', '🏖', '🤗', '📫', '🐐', '🍹', '🤌', '😋', '👂', '🌹', '🎯', '🆕', '💥', '🏗', '🍽', '🪨', '💖', '❣', '💈', '💹', '🧚', '🙇', '🏡', '👵', '🌑', '🐵', '✈', '🍑', '🧌', '🦑', '🌲', '🚆', '‼', '🤕', '🕳', '🥨', '🐒', '🍰', '🖕', '📸', '🤩', '♎', '📧', '⚕', '🧸', '🎊', '⚙', '🥞', '🥘', '🙌', '🚢', '🧎', '🧏', '🍟', '🧘', '🦆', '🧢', '🍄', '🐮', '🏟', '🥃', '👧', '🗂', '🏁', '🌛', '🖐', '🐢', '🫶', '🐗', '😷', '🥒', '🥛', '🎻', '🏙', '🖋', '🐿', '💞', '👀', '🤓', '💦', '🍗', '👷', '🛴', '☹', '🐻', '🍝', '🏇', '🐄', '🦓', '🧂', '🏵', '🙊', '🎓', '🐠', '👤', '🏚', '🔧', '🐷', '🟪', '🚨', '😶', '🪁', '📶', '📙', '✔', '📬', '🙀', '📚', '🫤', '🤮', '🥑', '🛜', '🌳', '😽', '🐔', '🐜', '😉', '🪵', '🩹', '🌫', '💿', '⏸', '🎦', '🥋', '🧻', '😇', '➿', '✳', '👻', '🛀', '🥅', '🧕', '🤵', '🪔', '🥕', '✏', '👹', '👶', '😯', '🦐', '☣', '📴', '🚦', '🤿', '❔', '🔇', '🛖', '📒', '✌', '👄', '🍱', '🟦', '😂', '👿', '📻', '🦰', '🔍', '♠', '🥼', '🪭', '🛤', '💷', '🌻', '🫅', '✍', '🔯', '🥣', '❓', '🀄', '🏐', '🫵', '🚂', '📏', '🍻'}

In [87]:
import pandas as pd
import emoji

def extract_emojis(text):
    return [char for char in str(text) if emoji.is_emoji(char)]

all_emojis = full_df['Text'].dropna().apply(extract_emojis)

flat_emojis = [emoji for sublist in all_emojis for emoji in sublist]

emoji_counts = pd.Series(flat_emojis).value_counts()
print(emoji_counts)

😭    31819
😂    24503
🤣    12716
🔥    10421
🥹     9272
     ...
👲        1
🧂        1
🗒        1
👓        1
♐        1
Name: count, Length: 1196, dtype: int64

In [88]:
# saves the emoji counts to a CSV file 
emoji_counts.to_csv('emoji_counts.csv', index=True)

In [84]:
full_df

                                                     Text
1                   He is right.. there was/is no chaos 🤡
9                                 Oooh. A manly man 🤡🤡😂😂😂
19      But Gavi is the problem and Bernabeu senior pl...
44            feel like i have two personalities lately 🤡
56                                              To late 🤡
...                                                   ...
839919  I take immense pride in washing dishes, pots, ...
839937                                       Time to ✅✅✅✅
839977                                 Happy Easter 🐣 ❤️✅
840017  Happy Easter everyone! Duty for today: Easter ...
840020      Yoghurt is the best way to clear a hangover ✅

[157786 rows x 1 columns]

In [81]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 157786 entries, 1 to 840020
Data columns (total 1 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Text    157786 non-null  object
dtypes: object(1)
memory usage: 2.4+ MB

In [86]:
full_df.to_csv('tweets1.csv', index=False)